job_targets: ["Data Scientist", "Machine Learning Engineer", "AI Consultant", "AI Engineer"]
preferred_locations: ["London", "United Kingdom", "Berlin", "Amsterdam"]
experience_keywords: ["Python", "SQL", "NLP", "MLOps", "Generative AI", "AI", "Python","tensorflow"]
salary_range: "£50,000 – £200,000"
visa_status: "UK Graduate Visa (PSW, 2025–2027)"
cv_path: "assets/Milind_cv_AI:ML_Engineer'25.pdf"
cover_letter_path: "assets/cover letter Flatiron health.pdf"
tone: "Professional"
application_style: "Detailed"
full_name: "Milind Bage"
email: "milind.gottlieb155@gmail.com"
phone: "+447840792939"

